export CONFIG_X86_SIMULATOR
CC = gcc
LD = gcc
AS = gcc

CFLAGS = -I port/x86 -Wall -m32 -g -fvar-tracking -DCONFIG_X86_SIMULATOR -I kernel/include -I apps

rosx: 
	$(CC) -o $@ apps/main.c -L. -lrosx $(CFLAGS)
         
clean:
	@rm -f rosx
