clean:
	rm -f rosx.bin
	rm -f rosx.hex
	rm -f rosx.elf
	rm -f rosx.list
	rm -f rosx.img
	rm -f rosx.bc
	rm -f rosx.lds
	rm -f include/asm
	rm -rf out
	rm -f rosx86
	rm -f librosx.a
	rm -rf validate
	rm -f validate.tar.gz

